### ISSUE TITLE
Looks like there is a problem with pin.sh

### ISSUE THREAD

**Issue by Haltz** [ucare-uchicago/FEMU#77]
`pin.sh`, which is used to enable stable performance, throws an error as below when being excuted.
```
  File "./ftk/qmp-vcpu-pin", line 36
    print "vCPU{}\'s tid {} already pinned, skipping".format(vcpuid, tid)
          ^
SyntaxError: invalid syntax
pid 2077565's current affinity list: 0-103
pid 2077565's new affinity list: 1-103
```
Maybe someone should fix it, or can anyone tell me is there something wrong about what i do ?
Thank you very much!

**Comment by Haltz** [comment]
And it seems like not just a syntax error. I have changed python from 2 to 3 and found a new problem.
```
 % ./pin.sh
Traceback (most recent call last):
  File "./ftk/qmp-vcpu-pin", line 30, in <module>
    srv.connect()
  File "/home/hd/repos/FEMU/build-femu/ftk/qmp.py", line 130, in connect
    self.__sock.connect(self.__address)
FileNotFoundError: [Errno 2] No such file or directory
taskset: invalid PID argument: '1-104'
```
I think the file is `qmp-sock`. Is there a way to fix it? 
Appreciate any suggestions from you guys!

**Comment by Haltz** [comment]
Looks like `query-cpus` command failed. I substitute it with `query-cpus-fast`, and my `qmp-vcpu-pin` as below works.
```
#!/usr/bin/python
# QEMU vCPU pinning tool
#
# Copyright (C) 2016 Red Hat Inc.
#
# Authors:
#  Maxime Coquelin <maxime.coquelin@redhat.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory
import argparse
import json
import os

from subprocess import call
from qmp import QEMUMonitorProtocol

pinned = []

parser = argparse.ArgumentParser(description='Pin QEMU vCPUs to physical CPUs')
parser.add_argument('-s', '--server', type=str, required=True,
                    help='QMP server path or address:port')
parser.add_argument('cpu', type=int, nargs='+',
                    help='Physical CPUs IDs')
args = parser.parse_args()

devnull = open(os.devnull, 'w')

srv = QEMUMonitorProtocol(args.server)
srv.connect()

for vcpu in srv.command('query-cpus-fast'):
    vcpuid = vcpu['cpu-index']
    tid = vcpu['thread-id']
    if tid in pinned:
        print("vCPU{}\'s tid {} already pinned, skipping".format(vcpuid, tid))
        continue

    cpuid = args.cpu[vcpuid % len(args.cpu)]
    print("Pin vCPU {} (tid {}) to physical CPU {}".format(vcpuid, tid, cpuid))
    try:
        call(['taskset', '-pc', str(cpuid), str(tid)], stdout=devnull)
        pinned.append(tid)
    except OSError:
        print("Failed to pin vCPU{} to CPU{}".format(vcpuid, cpuid))
```

**Comment by huaicheng** [comment]
Glad you figured it out. I didn't update the script according as FEMU is rebased on a newer version of QEMU.

Do you want to submit a pull request with your changes? I will test and merge it later. Thanks.

**Comment by Haltz** [comment]
My pleasure.
